### ISSUE TITLE
Group and sort the feature list by theme

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex.github.io#30]
## Summary

It would be nice to tidy up the feature list at https://moneymanagerex.org/.
Currently I'm overwhelmed by the amount of cards with their card-title, card-text and icon.
Probably cut of the text on the main view and enlarge it if you click on it.

### Basic example

Currently I see much text, which is larger than my 27" 1080p desktop screen can display.
On my smartphone screen it's even worse.

### Motivation

I think it should be better to sort the features by "most used" and group them by their category (as example transaction category or stock/asset category).
Also it would be better to cut of the text until you click on the card, otherwise I need to scroll too much.
And on my smartphone I'm lost.

**Comment by whalley** [comment]
Must admit, I don't really have an issue with it, and I can navigate the site well on my iPhone.

Though of course happy to consider improvements. I actually think the best thing would be to expend effort updating the feature sections as they are out-of-date and the screenshots really old (see https://github.com/moneymanagerex/moneymanagerex.github.io/issues/10).

I'm hoping users can contribute to this now we have the site in a Git repo.

**Comment by MartinX3** [comment]
![chrome_screenshot_06.03.2022 19_59_07 MEZ.png](https://user-images.githubusercontent.com/4518092/156938024-700ca38c-fef3-4e76-80af-a3e4439e8b10.png)

On Android it's a large page to scroll
Maybe the grouped functions should be in carousel elements?

**Comment by whalley** [comment]
...another option is using an [Accordian](https://getbootstrap.com/docs/5.0/components/accordion/) for the feature list.

**Comment by MartinX3** [comment]
S
