### ISSUE TITLE
Cut the description text 

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex.github.io#31]
## Summary

At https://moneymanagerex.org/ is a large description text, I need to scroll down until I see the features.
On my smartphone it's even worse.

### Basic example

I open the website on my smartphone and need to scroll and scroll until I see the features.

### Motivation

I think it should be easier for new people to see the benefits of MMEX instead of scrolling through a text wall.

**Comment by whalley** [comment]
@MartinX3 Do you have an example of a proposed layout? Is there another financial app site that you think has a better structure we could adopt?
