### ISSUE TITLE
Add a feature comparison table

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex.github.io#32]
## Summary

I want to see the benefits of MMEX versus the other tools instead of scrolling through much text.

### Basic example

I see text and text and need to get time to read though everything.

### Motivation

A new user who looks for a money tool probably just wants to easy list the available tools in the internet and compare them without reading through a text wall.
And sadly open source is only important for a minority of casual end users. :(

**Comment by whalley** [comment]
Think this is a great suggestion. Do you want to kick it off?

**Comment by whalley** [comment]
https://appmus.com/vs/money-manager-ex-vs-kmymoney

**Comment by MartinX3** [comment]
Thank you. :)

Sadly I need to write a maths exam at the end of the month and after that I first need to create a new website for my local sports club after my normal job.
So it will take time until I could start with this ticket.
If it's still open after that, I could start it.
But probably it could take months. :(
